(define (div-terms l1 l2)
  (if (empty-termlist? l1)
      (list (the-empty-termlist) (the-empty-termlist))
      (let ((t1 (first-term l1))
	    (t2 (first-term l2)))
	(if (> (order t2) (order t1))
	    (list (the-empty-termlist) l1)
	    (let ((new-c (div (coeff t1) (coeff t2)))
		  (new-o (- (order t1) (order t2))))
	      (let ((rest-of-result
		     (div-terms (sub-terms l1 (list (make-term new-o new-c)))
				l2)))
		(list (add-terms (make-term new-o new-c) (car rest-of-result))
		      (cadr rest-of-result))))))))

(define (div-poly p1 p2)
  (if (same-variable? (variable p1) (Variable p2))
      (div-terms (term-list p1) (term-list p2))
      (error "can't div poly with different vars")))