(define (or-gate a1 a2 output)
  (let ((inv-a (make-wire))
	(inv-b (make-wire))
	(c (make-wire)))
    (inverter a inv-a)
    (inverter b inv-b)
    (and-gate inv-a inv-b c)
    (inverter c output)
    'ok))