(define (ranking)
  (let ((betty (amb 1 2 3 4 5))
	(ethel (amb 1 2 3 4 5))
	(joan (amb 1 2 3 4 5))
	(kitty (amb 1 2 3 4 5))
	(mary (amb 1 2 3 4 5))

	(b (amb 0 1))
	(e (amb 0 1))
	(j (amb 0 1))
	(k (amb 0 1))
	(m (amb 0 1)))
    (require (distinct? (list betty ethel joan kitty mary)))

    (if (= b 0)
	(require (= kitty 2))
	(require (= betty 3)))
    (if (= e 0)
	(require (= ethel 1))
	(require (= joan 2)))
    (if (= j 0)
	(require (= joan 3))
	(require (= ethel 5)))
    (if (= k 0)
	(require (= kitty 2))
	(require (= mary 4)))
    (if (= m 0)
	(require (= mary 4))
	(require (= betty 1)))

    (list (list 'betty betty)
	  (list 'ethel ethel)
	  (list 'joan joan)
	  (list 'kitty kitty)
	  (list 'marry marry))))